# Site settings
title: Happy Birthday to 24-year-old 段志鹏
email: from his wife 涂芊宝
url: https://example.github.io
description: "今天是10月22日，段志鹏先生2019年的生日，我们从意大利终于搬到了挪威。这一年发生了很多重要的事情，比如我们结婚了，我们硕士毕业了，我们决定一起去挪威了。好像很多很多大事件，但是重要的‘我们’。我坐在桌前看着刚买的花花和远处的教堂，以及无比珍贵的奥斯陆阳光，真的觉得自己非常幸福，和逼志在一起."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: happy birthday to duanduan sir

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
